apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web # Название Pod
  labels: # Метки в формате key: value
    app: web
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
    - name: web # Название контейнера
      image: batcake/nginx-k8s-intro # Образ из которого создается контейнер
      volumeMounts:
        - name: app
          mountPath: /app
      ports:
        - name: web
          containerPort: 8000
  initContainers:
    - name: generate-index-html
      image: busybox:1.31
      command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
